# Generated by Django 4.2.7 on 2024-01-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monday', '0003_alter_project_stage_alter_project_structural_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='civil_defense',
            field=models.FileField(blank=True, null=True, upload_to='civil_defenses/'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_form',
            field=models.FileField(blank=True, null=True, upload_to='client_forms/'),
        ),
        migrations.AddField(
            model_name='project',
            name='deed',
            field=models.FileField(blank=True, null=True, upload_to='deeds/'),
        ),
        migrations.AddField(
            model_name='project',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='identities/'),
        ),
        migrations.AddField(
            model_name='project',
            name='land_survey',
            field=models.FileField(blank=True, null=True, upload_to='land_surveys/'),
        ),
        migrations.AddField(
            model_name='project',
            name='old_license',
            field=models.FileField(blank=True, null=True, upload_to='old_licenses/'),
        ),
        migrations.AddField(
            model_name='project',
            name='soil_test',
            field=models.FileField(blank=True, null=True, upload_to='soil_tests/'),
        ),
        migrations.AddField(
            model_name='project',
            name='water_authority',
            field=models.FileField(blank=True, null=True, upload_to='water_authorities/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('1', 'Sketch'), ('2', 'Sketch Review'), ('3', 'Approval Before Columns'), ('4', 'Awaiting Client Approval On Columns'), ('5', 'Implementation Phase'), ('6', 'Project Review In Autocad'), ('7', 'Ready For Printing After Review'), ('8', 'Review And Sign The Review Copy'), ('9', 'Ready To Receive The Review Copy'), ('10', 'Client Received The Review Copy'), ('11', 'Modifying Clients Notes'), ('12', 'Ready For Final Receipt'), ('13', 'Awaiting Completion Of The Plans'), ('14', 'Completed Projects'), ('15', 'Inactive Projects')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='structural_review',
            field=models.CharField(blank=True, choices=[('Working on it', 'Working On It'), ('Done', 'Done')], max_length=100, null=True),
        ),
    ]
